### PR TITLE
🐛 fix reading enum values from geos documentation

### LINKED ISSUE #39: Some enum values are incorrect: Start at 0, should start at 1
The [generateFunctions.mjs](https://github.com/chrispahm/geos-wasm/blob/main/generateFunctions.mjs) script assumes all enums start at zero. However, some enums like [GEOSWKBFlavors](https://libgeos.org/doxygen/geos__c_8h.html#a392dd5786d426c659b97803a5434e9b7), [GEOSBufCapStyles](https://libgeos.org/doxygen/geos__c_8h.html#a599f8ffb2d62e21b53b93d2c9c602d25) etc. start at 1.

The script should scrape the correct enum values from the top of the docs page.

### PR DESCRIPTION
**Pull request by mthh**
This will fix #39 (however I did not include the modified `src/addGeosFunctions.mjs`).

### CODE REVIEW

**Comment by chrispahm** [comment]
🚀  Thanks a lot @mthh! Can I merge this or will you continue to work on this PR?

**Comment by mthh** [comment]
You can merge it :)

**Comment by mthh** [comment]
But note that if we compile (with npm run make) after running generateFunctions.mjs, the `_GEOSGeom_transformXYZ_r` which is added in the GEOS_EMCC_FLAGS file (and which is not in the current GEOS_EMCC_FLAGS file) seems to cause an error :thinking: (but it isn't related to this PR)

**Comment by chrispahm** [comment]
Yes, that's a bug a bug indeed! → discussion in #43

**Pull request merged**
