### PR TITLE
Switch to WKB as data transfer format

### PR DESCRIPTION
**Pull request by chrispahm**

### CODE REVIEW

**Comment by sanak** [comment]
@chrispahm  
I could run `npm run performance` and got similar result as https://github.com/chrispahm/geos-wasm/issues/4#issuecomment-1620112018 on my M1 MacBook Pro + Node.js v18 environment.

```
% npm run performance

> geos-wasm@0.0.1 performance
> node test/performance.mjs

(node:96282) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Testing feature Simple
GEOS buffer method took 26 milliseconds to run 100 times.
Average time per iteration: 0 milliseconds.
@turf/turf buffer method took 51 milliseconds to run 100 times.
Average time per iteration: 1 milliseconds.
GEOS buffer method was 1.96x faster than @turf/turf buffer method.

Testing feature Australia
GEOS buffer method took 8011 milliseconds to run 100 times.
Average time per iteration: 80 milliseconds.
@turf/turf buffer method took 6597 milliseconds to run 100 times.
Average time per iteration: 66 milliseconds.
@turf/turf buffer method was 1.21x faster than GEOS buffer method.

Real life performance test
Buffering all geometries at once
GEOS buffer method took 320 milliseconds to run 1 times.
Average time per iteration: 320 milliseconds.
@turf/turf buffer method took 250 milliseconds to run 1 times.
Average time per iteration: 250 milliseconds.
@turf/turf buffer method was 1.28x faster than GEOS buffer method.

Buffering each geometry individually
GEOS buffer method took 278 milliseconds to run 1 times.
Average time per iteration: 278 milliseconds.
@turf/turf buffer method took 142 milliseconds to run 1 times.
Average time per iteration: 142 milliseconds.
@turf/turf buffer method was 1.96x faster than GEOS buffer method.
```

But, I noticed that `npm run test` failed, so it needs to be updated.
```
% npm run test

> geos-wasm@0.0.1 test
> rollup -c && node test/test.mjs

(node:96153) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

src/index.mjs → ./build/package/geos.esm.js, docs/assets/geos.esm.js...
(!) Circular dependencies
node_modules/@syncpoint/wkx/lib/geometry.js -> node_modules/@syncpoint/wkx/lib/point.js -> node_modules/@syncpoint/wkx/lib/geometry.js
node_modules/@syncpoint/wkx/lib/geometry.js -> node_modules/@syncpoint/wkx/lib/linestring.js -> node_modules/@syncpoint/wkx/lib/geometry.js
node_modules/@syncpoint/wkx/lib/geometry.js -> node_modules/@syncpoint/wkx/lib/polygon.js -> node_modules/@syncpoint/wkx/lib/geometry.js
...and 4 more
created ./build/package/geos.esm.js, docs/assets/geos.esm.js in 666ms
geos stderr: Aborted(both async and sync fetching of the wasm failed)
geos stderr: failed to asynchronously prepare wasm: RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info.
geos stderr: Aborted(RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info.)
file:///Users/sanak/Build/wasm/geos-wasm/build/package/geos.esm.js:8026
:
```
</details>

Otherwise, I think that it's fine.
(But, I am not familiar with byte array part, and checking that part will take a certain days for me...)

**Comment by chrispahm** [comment]
Nice thanks for having a look @sanak!
I'm receiving the same error when running the test file, will have a look again!

**Comment by chrispahm** [comment]
Alright, just published a few changes:
The error was a result of node not being able to find the .wasm binary. You can pass a function to `config.locateFile`, e.g. ```js
const geos = await initGeosJs({
  locateFile(path) {
    return "./path/or/url/geos.wasm"
   }
})
```
but, I think it's not very user friendly and doesn't work so well in environments like Observable. 
So now I compiled GEOS with the `-s SINGLE_FILE=1` flag, which bundles everything in a single JS file, but also increases the bundle size by ~33%. Personally, I think it's worth it since as a developer you don't have to worry about where the .wasm binary is located and importing the library "just works" without having to dig through the documentation first. But if you have a strong opinion against this I'd consider switching back!

**Comment by sanak** [comment]
I missed above comment...
I confirmed that `npm run test` passed.
Thanks!

**Pull request merged**
