### PR TITLE
Add missing C functions since 3.11 and 3.12

### LINKED ISSUE #23: Missing C functions since 3.11 and 3.12
I noticed that the following C functions (since 3.11 and 3.12) are missing in main branch.
It's not so urgent, but it would be nice to support these methods.

- since 3.11
  - [GEOSGeom_createRectangle](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2486-L2498)
  - [GEOSGeom_getExtent](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2780-L2798)
  - [GEOSRemoveRepeatedPoints](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3107-L3126)
  - [GEOSPolygonHullSimplify](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4010-L4032)
  - [GEOSPolygonHullSimplifyMode](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4045-L4070)
  - [GEOSLineMergeDirected](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4442-L4453)
  - [GEOSHilbertCode](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4534-L4554)
  - [GEOSGeom_transformXY](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4556-L4573)
  - [GEOSWKTReader_setFixStructure](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5368-L5378)
  - [GEOSWKBReader_setFixStructure](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5495-L5505)
- since 3.12
  - [GEOSGeomGetM](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2654-L2663)
  - [GEOSHasM](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2860-L2867)
  - [GEOSDisjointSubsetUnion](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3551-L3561)
  - [GEOSCoverageIsValid](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3795-L3821)
  - [GEOSCoverageSimplifyVW](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3836-L3851)
  - [GEOSLineSubstring](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4455-L4469)
  - [GEOSEqualsIdentical](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4773-L4787)
  - [GEOSPreparedContainsXY](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4906-L4920)
  - [GEOSPreparedIntersectsXY](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5006-L5020)
  - [GEOSSTRtree_build](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5140-L5151)

### PR DESCRIPTION
**Pull request by chrispahm**
fixes #23 

- Adds missing C Functions:
[GEOSGeom_createRectangle](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2486-L2498)
[GEOSGeom_getExtent](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2780-L2798)
[GEOSRemoveRepeatedPoints](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3107-L3126)
[GEOSPolygonHullSimplify](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4010-L4032)
[GEOSPolygonHullSimplifyMode](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4045-L4070)
[GEOSLineMergeDirected](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4442-L4453)
[GEOSHilbertCode](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4534-L4554)
[GEOSGeom_transformXY](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4556-L4573)
[GEOSWKTReader_setFixStructure](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5368-L5378)
[GEOSWKBReader_setFixStructure](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5495-L5505)
[GEOSGeomGetM](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2654-L2663)
[GEOSHasM](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2860-L2867)
[GEOSDisjointSubsetUnion](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3551-L3561)
[GEOSCoverageIsValid](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3795-L3821)
[GEOSCoverageSimplifyVW](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3836-L3851)
[GEOSLineSubstring](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4455-L4469)
[GEOSEqualsIdentical](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4773-L4787)
[GEOSPreparedContainsXY](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4906-L4920)
[GEOSPreparedIntersectsXY](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5006-L5020)
[GEOSSTRtree_build](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5140-L5151)
- Updates docs with new functions

### CODE REVIEW

**Comment by chrispahm** [comment]
@sanak would appreciate if you could have a look and check if I got it right!

**Comment by sanak** [comment]
@chrispahm 
> @sanak would appreciate if you could have a look and check if I got it right!

Sorry, I missed this PR for a quite long time... 🙇
I will check this in this week.

**Comment by sanak** [comment]
Well, there will be Japan frontend geo online tech meetup at 2024-05-18(Sat), so I will do this at that time...
https://osgeojp.connpass.com/event/317706/

**Comment by sanak** [comment]
@chrispahm Thanks for a lot of work!
I added some comments in the following `Check` column, so please checking these. :bow:
(The last `GEOSSTRtree_build`, GEOS parameter comment is missing, so I will create an issue for GEOS side, later.)

| Function name                   | GEOS CAPI definition<br>(`capi/geos_c.h.in`) | GEOS-WASM definition<br>(`src/allCFunctions.mjs`) | GEOS-WASM doc<br>(`docs/functions/geos.*.md`) | Check |
|---------------------------------|----------------------------------------------|---------------------------------------------------|---------------------------------|-------|
| GEOSGeom_createRectangle | [#L2486-L2498](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2486-L2498) | [#L3316-L3342](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L3316-L3342) | [GEOSGeom.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSGeom.md#geosgeosgeom_createrectangle--number-) | o |
| GEOSGeom_getExtent | [#L2780-L2798](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2780-L2798) | [#L3520-L3548](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L3520-L3548) | [GEOSGeom.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSGeom.md#geosgeosgeom_getextent--number-) | x (no `_r`) |
| GEOSRemoveRepeatedPoints | [#L3107-L3126](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3107-L3126) | [#L1398-L1434](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L1398-L1434) | [GEOSRemoveRepeatedPoints.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSRemoveRepeatedPoints.md) | o |
| GEOSPolygonHullSimplify | [#L4010-L4032](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4010-L4032) | [#L2483-L2523](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L2483-L2523) | [GEOSPolygonHullSimplify.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSPolygonHullSimplify.md) | o |
| GEOSPolygonHullSimplifyMode | [#L4045-L4070](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4045-L4070) | [#L2524-L2568](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L2524-L2568) | [GEOSPolygonHullSimplify.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSPolygonHullSimplify.md##geosgeospolygonhullsimplifymode--number-) | o |
| GEOSLineMergeDirected | [#L4442-L4453](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4442-L4453) | [#L2639-L2665](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L2639-L2665) | [GEOSLineMerge.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSLineMerge.md#geosgeoslinemergedirected--number-) | o |
| GEOSHilbertCode | [#L4534-L4554](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4534-L4554) | [#L4693-L4726](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L4693-L4726) | [GEOSHilbertCode.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSHilbertCode.md) | x (none `_r` has `handle`) |
| GEOSGeom_transformXY | [#L4556-L4573](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4556-L4573) | [#L4727-L4757](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L4727-L4757) | [GEOSGeom.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSGeom.md#geosgeosgeom_transformxy--number-) | o |
| GEOSWKTReader_setFixStructure | [#L5368-L5378](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5368-L5378) | [#L3651-L3669](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L3651-L3669) | [GEOSWKTReader.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSWKTReader.md#geosgeoswktreader_setfixstructure-) | o |
| GEOSWKBReader_setFixStructure | [#L5495-L5505](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5495-L5505) | [#L3856-L3874](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L3856-L3874) | [GEOSWKBReader.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSWKBReader.md#geosgeoswkbreader_setfixstructure-) | o |
| GEOSGeomGetM | [#L2654-L2663](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2654-L2663) | [#L2163-L2183](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L2163-L2183) | [GEOSGeom.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSGeom.md#geosgeosgeomgetm--number-) | o |
| GEOSHasM | [#L2860-L2867](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L2860-L2867) | [#L2799-L2814](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L2799-L2814) | [GEOSHasM.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSHasM.md) | o |
| GEOSDisjointSubsetUnion | [#L3551-L3561](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3551-L3561) | [#L1651-L1673](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L1651-L1673) | [GEOSDisjoint.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSDisjoint.md#geosgeosdisjointsubsetunion--number-) | o |
| GEOSCoverageIsValid | [#L3795-L3821](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3795-L3821) | [#L1693-L1741](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L1693-L1741) | [GEOSCoverageIsValid.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSCoverageIsValid.md) | o |
| GEOSCoverageSimplifyVW | [#L3836-L3851](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L3836-L3851) | [#L1742-L1794](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L1742-L1794) | [GEOSCoverageSimplifyVW.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSCoverageSimplifyVW.md) | o |
| GEOSLineSubstring | [#L4455-L4469](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4455-L4469) | [#L2666-L2690](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L2666-L2690) | [GEOSLineSubstring.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSLineSubstring.md) | o |
| GEOSEqualsIdentical | [#L4773-L4787](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4773-L4787) | [#L493-L519](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L493-L519) | [GEOSEquals.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSEquals.md#geosgeosequalsidentical--number-) | o |
| GEOSPreparedContainsXY | [#L4906-L4920](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L4906-L4920) | [#L4141-L4165](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L4141-L4165) | [GEOSPrepare.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSPrepare.md#geosgeospreparedcontainsxy--number-) | o |
| GEOSPreparedIntersectsXY | [#L5006-L5020](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5006-L5020) | [#L4280-L4304](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L4280-L4304) | [GEOSPrepare.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSPrepare.md#geosgeospreparedintersectsxy--number-) | o |
| GEOSSTRtree_build | [#L5140-L5151](https://github.com/libgeos/geos/blob/3.12.0/capi/geos_c.h.in#L5140-L5151) | [#L4419-L4443](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/src/allCFunctions.mjs#L4419-L4443) | [GEOSSTRtree.md](https://github.com/chrispahm/geos-wasm/blob/add-missing-c-functions/docs/functions/geos.GEOSSTRtree.md#geosgeosstrtree_build--number-) | x (`number` arg for `tree` is missing in `Module.cwrap` last arg) |

**Comment by chrispahm** [comment]
superseeded by #35

**Pull request closed without merging**
